<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClubContext\ClubContext.csproj" />
    <ProjectReference Include="..\CompetitionExecutionContext\CompetitionExecutionContext.csproj" />
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\EventSchedulingContext\EventSchedulingContext.csproj" />
    <ProjectReference Include="..\HorseRider\HorseRiderContext.csproj" />
    <ProjectReference Include="..\UserManagementContext\UserManagementContext.csproj" />
  </ItemGroup>

</Project>
