import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "./components/NavBar"
import TopBar from "./components/Topbar" 
import "./globals.css";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <TopBar/>
        <div className="flex flex-1">
          <NavBar/>
          <main className="flex-1 bg[#f0f4ff] p-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
